name: GOAT Compile uno
 
on:
  push:
    branches:
      - main
 
jobs:
  integration:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
 
    steps:
      - name: "Obteniendo ultima version del codigo"
        uses: actions/checkout@v3
 
      - name: "Instalacion Java"
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "Instalar python"
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: "Instalar requests"
        run: pip3 install requests
 
      - name: "Compilacion"
        run: ./mvnw clean install
 
      - name: "Verificar paquete"
        run: ls -ltra target
 
      - name: "Dependency Check"
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: 'WebGoat'
          path: '.'
          format: 'XML'
          out: 'reports'

      - name: "Reporte dependecy check"
        run: |
          cd reports/
          python3 nuevo.py -f dependency-check-report.xml -t "Dependency check"
        
      # - name: "Upload SARIF report"
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: ${{github.workspace}}/reports
      #     checkout_path: ${{github.workspace}}/reports  
 
      - name: "Verificar reporte"
        run: ls -ltra reports
 
      - name: "Instalando Horusec"
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest-beta
 
      - name: "Horusec -SAST"
        run: horusec start -p="./"
 
      - name: "Imagen Docker"
        run: |
          docker build -f Dockerfile . -t webgoat/test
          docker images
 
      - name: "Run Trivy vulnerability scanner"
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'webgoat/test'
          timeout: 10m0s
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          scanners: vuln,secret,config
          format: 'json'
          output: 'reporteTr.json'
        continue-on-error: true

      - name: "Reporte trivy"
        run: |
          python3 nuevo.py -f reporteTr.json -t "Trivy Scan"
         
      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: 'trivy-results.sarif'
      #     category: 'code'
 
      - name: "Contenedor"
        run: docker run -d -p 8080:80 --name cod webgoat/test
    
      - name: "Listado"
        run: docker ps -a
 
      - name: "Iniciar"
        run: docker container start cod

      # - name: "Reporte"
      #   run: |
      #     trivy -f json -o reporteTr.json webgoat/test 
      #     python3 nuevo.py -f reporteT.json -t "Trivy Scan"
 
      - name: "Installing Arachni"
        run: |
          wget https://github.com/Arachni/arachni/releases/download/v1.6.1.3/arachni-1.6.1.3-0.6.1.1-linux-x86_64.tar.gz
          tar -xvf arachni-1.6.1.3-0.6.1.1-linux-x86_64.tar.gz
 
      - name: "Finding IP"
        run: ip_var=$(docker inspect webgoat/test | grep "IPAddress" | tail -1 | cut -d ',' -f 4)
 
      - name: "Executing Arachni"
        run: ./arachni-1.6.1.3-0.6.1.1/bin/arachni --check=* http://$ip_var:8080/WebGoat/login
 
      - name: "Crear Contenedor"
        run: |
          docker container stop cod
          docker container rm cod

      