name:  Compile image docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull PHP image
        run: sudo docker pull php:8.2-cli

     

      - name: copy code into image
        run: sudo docker build -t prueba .

      - name: list Docker images
        run: sudo docker images

    