name: GOAT Compile

on:
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
   

    steps:
      - name: "Obteniendo ultima version del codigo"
        uses: actions/checkout@v3

      - name: "Instalacion Java"
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "Compilacion"
        run: ./mvnw clean install

      - name: "Verificar paquete"
        run: ls -ltra target

      - name: "Dependency Check"
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: 'WebGoat'
          path: '.'
          format: 'HTML'
          out: 'reports'

      - name: "Verificar reporte"
        run: ls -ltra reports

      - name: "Instalando Horusec"
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest-beta

      - name: "Horusec - SAST"
        run:  horusec start -p="./"

      - name: "Generación de imagen de docker"
        run: |
          IMAGE_NAME="docker.io/my-organization/my-app:${{ github.sha }}"
          docker build -f Dockerfile -t $IMAGE_NAME .
          echo "Image Reference: $IMAGE_NAME"

      - name: "Instalar Trivy"
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
          sudo dpkg -i trivy_0.18.3_Linux-64bit.deb
      
      - name: "Ejecutar escáner de vulnerabilidades Trivy"
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.integration.outputs.image_name }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      
      - name: "Crear y ejecutar contenedor Docker"
        run: |
          docker run -d -p 8080:80 $IMAGE_NAME
      
      - name: "Esperar a que el contenedor se inicie"
        run: sleep 10

      - name: "Verificar estado del contenedor"
        run: docker ps | grep $IMAGE_NAME

      - name: "Manejo de errores si el contenedor no se encuentra"
        run: |
          if ! docker ps | grep -q $IMAGE_NAME; then
            echo "Error: El contenedor no se ha creado correctamente."
            exit 1
          fi

      - name: "Confirmación de finalización"
        run: echo "El flujo de trabajo se ha completado con éxito."
        

 


      




        